spring:
  profiles:
    active: local
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-database.yml
#  TODO: ライブラリが出揃って適切に修正すれば不要になりそう
  autoconfigure:
    exclude:
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisLanguageDriverAutoConfiguration

# for local / ut
---
spring:
  config:
    activate:
      on-profile:
        - local
        - ut

cors:
  allow-origins:
    - http://127.0.0.1:3000
    - http://localhost:3000

# for dev / stg / prod
---
spring:
  config:
    activate:
      on-profile:
        - dev
        - stg
        - prod

cors:
  allow-origins:
    - ${ALLOW_ORIGIN}
